apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "fe-yunti.labels" . | nindent 4 }}
spec:
  http:
    - name: main
      match:
        hosts:
          {{- range .Values.ingress.hosts }}
          - {{ .host | quote }}
          {{- end }}
        paths:
          - /*
      backends:
        - serviceName: {{ include "fe-yunti.fullname" . }}
          servicePort: {{ .Values.service.port }}
