image:
  repository: 121875945917.dkr.ecr.ap-southeast-1.amazonaws.com/apisix/go-plugin-runner
  pullPolicy: IfNotPresent
  tag: latest

apisix:
  logs:
    enableAccessLog: true

  gateway:
    type: LoadBalancer
  
  ingress-controller:
    enabled: true
    config:
      apisix:
        serviceNamespace: apisix
  
  serviceMonitor:
    enabled: true
  
  dashboard:
    enabled: false
    config:
      authentication:
        secert: secert
        expireTime: 3600
        users:
          - username: admin
            password: admin
    
  etcd:
    enabled: true
    nodeSelector:
      kubernetes.io/arch: amd64
