{{- $easi_resources := ternary .Values.prodResources .Values.resources (eq .Values.easi.runenv "production") -}}
{{- $easi_autoscaling := ternary .Values.prodAutoscaling .Values.autoscaling (eq .Values.easi.runenv "production") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wetv-gateway.fullname" . }}
  labels:
    {{- include "wetv-gateway.labels" . | nindent 4 }}
spec:
{{- if not $easi_autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "wetv-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "wetv-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wetv-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq .Values.easi.serviceLevel "S" }}
      priorityClassName: easi-s
      {{- end }}
      {{- if eq .Values.easi.serviceLevel "A" }}
      priorityClassName: easi-a
      {{- end }}
      terminationGracePeriodSeconds: 45
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          env:
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml $easi_resources | nindent 12 }}
          volumeMounts:

      volumes:

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if has .Values.image.platform .Values.context.platforms }}
      nodeSelector:
        kubernetes.io/arch: {{ .Values.image.platform }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
