apiVersion: v1
kind: Service
metadata:
  name: {{ include "common-service.fullname" . }}
  labels:
    {{- include "common-service.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.check.url }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "common-service.selectorLabels" . | nindent 4 }}
