apiVersion: v1
kind: Service
metadata:
  name: {{ include "job-executor.fullname" . }}
  labels:
    {{- include "job-executor.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.check.url }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "job-executor.selectorLabels" . | nindent 4 }}
