 on:
   workflow_run:
     workflows: ["pages-build-deployment"]
     types: [completed]

 jobs:
   on-success:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - run: echo "pages-build-deployment workflow was a success"

   on-failure:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
     steps:
       - run: echo "pages-build-deployment workflow was a failure"
